### ISSUE TITLE
При выполнении команды ошибка docker: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by vilshansky** [Advance-Technologies-Foundation/globalsearch-cli#5]
Привет! 

При выполнении команды на стороне клиента:

docker run -it --rm \ -v /tmp/gs-out:/app/out \ -v $(which docker):/usr/bin/docker \ -v /var/run/docker.sock:/var/run/docker.sock \ bpmonlinebuild/globalsearch-cli:0.0.2

ошибка:

bytecode@docker-copy:/$ docker run -it --rm \ -v /tmp/gs-out:/app/out \ -v $(which docker):/usr/bin/docker \ -v /var/run/docker.sock:/var/run/docker.sock \ bpmonlinebuild/globalsearch-cli:0.0.2
docker: invalid reference format.
See 'docker run --help'.

Также пробовали обернуть в кавычки:

docker run -it --rm -v "/tmp/gs-out:/app/out" -v "$(which docker):/usr/bin/docker" -v "/var/run/docker.sock:/var/run/docker.sock" bpmonlinebuild/globalsearch-cli:0.0.1

Но возникает другая ошибка:

? What would you like to do? Make logs of the docker containers
docker: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory
Error: Command failed: docker ps --filter "label=service=gs" -a --format "table {{.Names}}      {{.Ports}}      {{.Status}}     {{.RunningFor}} {{.Image}}" >> out/gs-CONTAINERS.log
    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:647:15)
    at Function.<anonymous> (/app/build/bundle.js:48337:30)
    at step (/app/build/bundle.js:48322:23)
    at Object.next (/app/build/bundle.js:48303:53)
    at /app/build/bundle.js:48297:71
    at new Promise (<anonymous>)
    at __awaiter (/app/build/bundle.js:48293:12)
    at Function.Docker._getContainers (/app/build/bundle.js:48332:16)
    at Function.<anonymous> (/app/build/bundle.js:48442:47) {
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 13,
  stdout: null,
  stderr: null
}

![image](https://user-images.githubusercontent.com/69623341/90109466-8b2a0680-dd54-11ea-8556-f817c8b0a1f5.png)

Возможно какие-то компоненты docker должны быть установлены или версия docker должна быть одной из последних?

Спасибо!

**Comment by sergeytkachenko** [comment]
Видимо эта ошибка связана с тем, что контейнеры не были запущены, и при выборке их через docker ps, скрипт свалился, так как это исключительная, не обрабатываемая ситуация. Проверим, поправим в сл версии.
